### ISSUE TITLE
Student HTML page

### ISSUE THREAD

**Issue by Pogut** [silvehh/anything-SOEN341_Project_F24#50]

**Comment by Frankies1002** [comment]
- [ ] Create a field for the users teammates
- [ ] Make sure teammates are visible to the user
- [ ] Make teammates clickable for edit
- [ ] Html page for teammates
- [ ] Redirect user to a new page for evaluation
- [ ] Create a form for basic evaluation
- [ ] Implement the form into an html page for basic evaluation
- [ ] Create a dimensional assessment form 
- [ ] Implement the the dimensional form into an html page with comments 
- [ ] Ensure Conceptual Contribution, Practical contribution Work ethic
- [ ] Create a confirmation page
- [ ] Implement all the page on the website
